name: enxolist
description: "EnxoList - Um aplicativo de enxoval."

version: 2.0.3+8

environment:
  sdk: '>=3.2.0-140.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #token/db
  shared_preferences: ^2.2.2
  
  #db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #http
  dio: ^5.4.0

  #di
  get_it: ^7.6.6
  injectable: ^2.3.2

  #data management
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  path_provider: ^2.1.2

  #mock
  mockito: ^5.4.4
  
  #state
  mobx: ^2.3.0+1  
  flutter_mobx: ^2.2.0+2
  mobx_codegen: ^2.6.0+1

  #firebase
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0

  #presentation  
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.3.1
  pinch_zoom: ^2.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  intl: ^0.19.0
  provider: ^6.1.2
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.0
  font_awesome_flutter: ^10.7.0
  crop_your_image: ^1.1.0
  google_maps_flutter: ^2.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/imgs/icon.png
    - assets/imgs/undraw/nodata.png
    - assets/imgs/login_image.png
    - assets/imgs/text_auth.png
    - assets/imgs/avatares/
    - assets/icon/icon.png
    - assets/imgs/onboard/

  fonts:
    - family: JustMeAgainDownHere
      fonts:
        - asset: assets/fonts/JustMeAgainDownHere-Regular.ttf
    - family: MarkaziText
      fonts:
        - asset: assets/fonts/MarkaziText-Regular.ttf
        - asset: assets/fonts/MarkaziText-Medium.ttf
        - asset: assets/fonts/MarkaziText-Bold.ttf
        - asset: assets/fonts/MarkaziText-SemiBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21