// Mocks generated by Mockito 5.4.4 from annotations
// in enxolist/test/data/repositories/product/product_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i9;

import 'package:dio/src/response.dart' as _i3;
import 'package:enxolist/data/data_source/product/product_remote_datasource_online.dart'
    as _i5;
import 'package:enxolist/data/models/product/product_model.dart' as _i8;
import 'package:enxolist/domain/entities/product/product_entity.dart' as _i4;
import 'package:enxolist/domain/response/product_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductResponse_0 extends _i1.SmartFake
    implements _i2.ProductResponse {
  _FakeProductResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductEntity_2 extends _i1.SmartFake implements _i4.ProductEntity {
  _FakeProductEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSourceOnline].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSourceOnline extends _i1.Mock
    implements _i5.ProductRemoteDataSourceOnline {
  MockProductRemoteDataSourceOnline() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ProductResponse> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue:
            _i6.Future<_i2.ProductResponse>.value(_FakeProductResponse_0(
          this,
          Invocation.method(
            #getProducts,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ProductResponse>);

  @override
  _i6.Future<_i2.ProductResponse> getProductsByCategory(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [categoryId],
        ),
        returnValue:
            _i6.Future<_i2.ProductResponse>.value(_FakeProductResponse_0(
          this,
          Invocation.method(
            #getProductsByCategory,
            [categoryId],
          ),
        )),
      ) as _i6.Future<_i2.ProductResponse>);

  @override
  _i6.Future<String> deleteProduct(_i4.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [product],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #deleteProduct,
            [product],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i3.Response<dynamic>> updateWasBought(
          _i4.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWasBought,
          [product],
        ),
        returnValue:
            _i6.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #updateWasBought,
            [product],
          ),
        )),
      ) as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i4.ProductEntity> createProduct(
    _i8.ProductModel? product, {
    _i9.File? imageFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [product],
          {#imageFile: imageFile},
        ),
        returnValue: _i6.Future<_i4.ProductEntity>.value(_FakeProductEntity_2(
          this,
          Invocation.method(
            #createProduct,
            [product],
            {#imageFile: imageFile},
          ),
        )),
      ) as _i6.Future<_i4.ProductEntity>);

  @override
  _i6.Future<_i4.ProductEntity> editProduct(
    _i8.ProductModel? product, {
    _i9.File? image,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [product],
          {#image: image},
        ),
        returnValue: _i6.Future<_i4.ProductEntity>.value(_FakeProductEntity_2(
          this,
          Invocation.method(
            #editProduct,
            [product],
            {#image: image},
          ),
        )),
      ) as _i6.Future<_i4.ProductEntity>);
}
